name: Publish Docs

on:
  push:
    tags:
      - 'docs'
      - 'docs-*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: docs-deploy
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'

      - run: pip install mkdocs-material pymdown-extensions

      - name: Deploy to GitHub Pages
        working-directory: docs/user_manual
        run: mkdocs gh-deploy --force
